### ISSUE TITLE
add to wallet button on order executed sucess page

### ISSUE THREAD

**Issue by karacurt** [mousehaunt/mousehaunt.com#126]
Idk if there is a button "add to wallet" when we buy some asset. If not, it would be great to add, especially for newcomers that doesn't have the CA for each booster

**Comment by juo-dev** [comment]
![image](https://user-images.githubusercontent.com/45723253/150410263-639b5ee8-8242-4f90-b495-e102363d1aa0.png)

![image](https://user-images.githubusercontent.com/45723253/150410545-251ef0fd-6d2c-4cdc-a839-fddd73478439.png)

**Comment by juo-dev** [comment]
Released. Marketplace v1.0
