### ISSUE TITLE
big value for price gets a white screen

### ISSUE THREAD

**Issue by karacurt** [mousehaunt/mousehaunt.com#130]
999999999999999999999999999999999999999... on "price", it goes to a white screen

![unknown](https://user-images.githubusercontent.com/38267570/150151096-429eda73-c437-4b29-bcb2-6d2335d7e50b.png)

**Comment by aviggiano** [comment]
Let's just put a hard limit, like ten nines: 9999999999

**Comment by juo-dev** [comment]
Released. Marketplace v1.0
