### ISSUE TITLE
fix toast message "unsuficient balance"

### ISSUE THREAD

**Issue by karacurt** [mousehaunt/mousehaunt.com#132]
On the internal order screen, when the user doesn't have enough funds to execute an order, the toaster message has a mistake. It says "Unsufficient balance", but should be "Insufficient balance" or "Insufficient funds" (which is the usual message). The first word begins with "In", not "Un"

![image](https://user-images.githubusercontent.com/38267570/150154868-fd87d2f1-a8b1-47e2-beaa-cc4a00c15852.png)

**Comment by juo-dev** [comment]
Released. Marketplace v1.0
