### ISSUE TITLE
remove transparency from logo on footer on order[ID] details page

### ISSUE THREAD

**Issue by karacurt** [mousehaunt/mousehaunt.com#136]
On the internal order screen, the background is over the game logo and social icons. It shouldn't be.

![image](https://user-images.githubusercontent.com/38267570/150156188-2e99e97e-273f-4142-9a06-b52429cdecb4.png)

**Comment by karacurt** [comment]
solved on https://github.com/mousehaunt/mousehaunt.com/commit/9b4a0a73b4c1a18f6ee40bb8485965b088c1e76a

**Comment by juo-dev** [comment]
Released. Marketplace v1.0
