### ISSUE TITLE
remove 'booster' word

### ISSUE THREAD

**Issue by karacurt** [mousehaunt/mousehaunt.com#137]
We recently had the definition that we're abandoning the word "Booster" in favor of "Box". Are we going to make that transition now, or is that an "ongoing effort"? Right now, we're still using the word "Booster" everywhere.  

edit - waiting for a final decision, needs to be discussed 

![image](https://user-images.githubusercontent.com/38267570/150156405-866f570f-278c-4604-b6ff-845ee9a98950.png)
![image](https://user-images.githubusercontent.com/38267570/150156425-96ada191-2f8c-4a0c-895b-84a84eff0e8d.png)
![image](https://user-images.githubusercontent.com/38267570/150156448-3812b69e-1bcb-47db-afeb-53c5d586c0b4.png)
![image](https://user-images.githubusercontent.com/38267570/150156622-5f9f03f0-ce88-4b36-ac5d-b9280cb1febf.png)

**Comment by daniportugalgit** [comment]
The only Box is the Heroic Box. All other boosters are boosters.
