### ISSUE TITLE
Investigate: Check allowance or balance rounded value - insufficient funds on create orders

### ISSUE THREAD

**Issue by juo-dev** [mousehaunt/mousehaunt.com#170]
ticket-0704

transaction failed (transactionHash="0x81dcd83abe7343caa019d5d1041353c96df441f1866139f87c9d135a4a4aefd5", transaction={"hash":"0x81dcd83abe7343caa019d5d1041353c96df441f1866139f87c9d135a4a4aefd5","type":0,"accessList":null,"blockHash":null,"blockNumber":null,"transactionIndex":null,"confirmations":0,"from":"0xee7dA487Ecd7e08EA42E72564d00Fc92351ceA6B","gasPrice":{"type":"BigNumber","hex":"0x012a05f200"},"gasLimit":{"type":"BigNumber","hex":"0x03483c"},"to":"0x85579a32eC2a20a374a9b8C1aa9B526760830b95","value":{"type":"BigNumber","hex":"0x00"},"nonce":409,"data":"0x94f611340000000000000000000000000000000000000000000000000000000000000124","r":"0x200217a41f4eac8e9c3765bb5bdf54fbe1601bbbc5c2dacc1fe88d591f4f4730","s":"0x477e63a9232fe0b5c8a8edc038ae6806a123dadbd0ec523c0397bd8ce6ebb309","v":148,"creates":null,"chainId":56}, receipt={"to":"0x85579a32eC2a20a374a9b8C1aa9B526760830b95","from":"0xee7dA487Ecd7e08EA42E72564d00Fc92351ceA6B","contractAddress":null,"transactionIndex":223,"gasUsed":{"type":"BigNumber","hex":"0x033a95"},"logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","blockHash":"0xc117534393a9d6620f6e3e1d809e3b6d988f75f382c40ceed7eee2631c2949ec","transactionHash":"0x81dcd83abe7343caa019d5d1041353c96df441f1866139f87c9d135a4a4aefd5","logs":[],"blockNumber":14678909,"confirmations":3,"cumulativeGasUsed":{"type":"BigNumber","hex":"0x01a2f307"},"status":0,"type":0,"byzantium":true}, code=CALL_EXCEPTION, version=providers/5.5.2)

**Comment by aviggiano** [comment]
https://bscscan.com/tx/0x81dcd83abe7343caa019d5d1041353c96df441f1866139f87c9d135a4a4aefd5

**Comment by juo-dev** [comment]
Investigamos as transações de falha (2 tentativas de executeOrder) e a posterior de sucesso e verificamos que:
- A quantidade de gas estimada estava dentro do aceitável
- A order estava ativa
- Não identificamos erro de arredontamento

Conseguimos reproduzir o cenário no teste. Criamos uma ordem no valor de 45MHT e em uma conta nova add apenas os 45MHT necessários para executar a ordem e ela foi executada com sucesso.

Não encontramos traços de erro na lógica do negócio (nem no contrato nem no site). 

Tentamos recuperar o saldo da conta no bloco da execução da transação, mais o balance history retorna 0 (parece que tanto no ethereum qndo na bsc apenas os últimos 256 blocos retornam o valor). 

Conclusão: não conseguimos reproduzir o erro nem identificar a real natureza dele. Sendo assim, nos percebe que talvez tenha havido uma instabilidade na rede no caso ocorrido.

Estaremos fechando o ticket associado.
