### ISSUE TITLE
Warn users when they have the wrong network selected

### ISSUE THREAD

**Issue by aviggiano** [mousehaunt/mousehaunt.com#36]
- [x] Probably using a toast
- [x] Button to `onClick` Switch Network
- [x] We might as well disable the create order button, and other CTAs.

**Comment by aviggiano** [comment]
I switched the network and didn't get any message that I'm on the wrong network.

I tried to open the site from scratch with the wrong network and I didn't see any warning, the only visual feedback I received was not seeing the items for sale.

I even tried to change the network and the site didn't recognize it automatically, I had to press F5 to see the itens for sale.

Sending an example message to notify the network, when I enter the Polygon network it automatically removes this popup and enters the normal site
![network](https://user-images.githubusercontent.com/3029017/148683332-3d271f1f-65a3-473d-b82f-123c13bd89c4.png)

**Comment by juo-dev** [comment]
- [ ] Update toast
- [ ] Nofity user on changed network
