### ISSUE TITLE
Check account connect

### ISSUE THREAD

**Issue by juo-dev** [mousehaunt/mousehaunt.com#43]
- Wallet is not connected but site show the address in header
 
![image](https://user-images.githubusercontent.com/45723253/148591708-2d9f70f0-5202-47a3-9907-ce9c27d38df6.png)

**Comment by aviggiano** [comment]
This is because you have multiple accounts on your metamask wallet, but only the `0xDD5` is connected, NOT the one you have selected (`0x923`)

**Comment by karacurt** [comment]
addressed on #104
