### ISSUE TITLE
Improve filters

### ISSUE THREAD

**Issue by aviggiano** [mousehaunt/mousehaunt.com#52]
- [x] rarity order should be LEGENDARY, EPIC, RARE, GENESIS
- [ ] <del> It will be very good if we have filters like: price low to high, etc</del>
- [x] when your clear all filters, they didn't go back visually
- [x] Word filter should search for rarity
- [x] Slider step is "exponential" and not "linear" (e.g. airbnb) (optional)

![filters](https://user-images.githubusercontent.com/3029017/148662433-fb06b9ce-e09f-472d-9818-da1806c8d465.png)

![rarity](https://user-images.githubusercontent.com/3029017/148683089-79342ecc-de18-4336-9b75-45a73d5f38d0.png)

https://user-images.githubusercontent.com/3029017/149996634-abf8342d-7ab8-4c5c-8cc5-362b73598d03.MP4
See here that 50% of the slider is NOT 50% of max value. See that 25% of the slider is NOT 1/4 of the max value. The slider gets more "detailed" near min value and less "detailed" near max value

**Comment by aviggiano** [comment]
<img width="531" alt="Screen Shot 2022-01-09 at 23 02 31" src="https://user-images.githubusercontent.com/3029017/148710685-221d285b-ae41-41eb-b249-4ffd11aae3c5.png">

**Comment by aviggiano** [comment]
@karacurt if you're out of P2, can you help out with this one?

maybe take tasks from bottom to top so that we hopefully finish in the middle

**Comment by juo-dev** [comment]
- [ ] It will be very good if we have filters like: price low to high, etc

Moved to issue #129

**Comment by juo-dev** [comment]
Released. Marketplace v1.0
