### ISSUE TITLE
Create order "amount" is not clear if total is per booster or per total

### ISSUE THREAD

**Issue by aviggiano** [mousehaunt/mousehaunt.com#53]
# Description

- Radio button: "Bulk order" / "Single order"
- Change "Price" label to "Unit Price"
- Omit "Amount" and add checkbox to allow "Bulk order". When the user checks "Bulk Order", adds "Amount" field and add "Total price" as a calculated field (e.g., 50 unit price, 3 amount, total price = 150)
- Single order: do not show "Amount" field (because it is 1)
- Bulk order: Add "Notice" tag saying all boosters **will not** be sold separately. 

# Attachments

<img width="420" alt="Screen Shot 2022-01-08 at 19 51 25" src="https://user-images.githubusercontent.com/3029017/148662514-d7012818-899d-4800-bd44-6d51f846a304.png">

**Comment by aviggiano** [comment]
<img width="741" alt="Screen Shot 2022-01-09 at 10 08 41" src="https://user-images.githubusercontent.com/3029017/148683412-b5a17423-1d16-4d89-97ef-46996a5540a0.png">

**Comment by aviggiano** [comment]
> The buttons of Info doesnt work here, i dont know if i put 10 genesis boosters for sale if the price is for each individualy or for the 10 of them together. If buying i dont have how to choose how many to buy so i figure out that im buying all at once by the price it shows

**Comment by juo-dev** [comment]
Released. Marketplace v1.0
