### ISSUE TITLE
Double transaction makes order revert

### ISSUE THREAD

**Issue by aviggiano** [mousehaunt/mousehaunt.com#54]
![double-transaction](https://user-images.githubusercontent.com/3029017/148662591-ffb23398-1da0-4687-aab0-724e7943db69.png)

![screenshot-2022-01-08-19-53-40](https://user-images.githubusercontent.com/3029017/148662589-6162bd66-c84a-4ca3-89fa-d51ee0a2c704.png)

**Comment by aviggiano** [comment]
This should've been fixed, but I couldn't reproduce

**Comment by karacurt** [comment]
couldn`t reproduce either, probably addressed by some of other features
