### ISSUE TITLE
Add tooltip in information icons on /marketplace/create

### ISSUE THREAD

**Issue by aviggiano** [mousehaunt/mousehaunt.com#58]
Each icon should explain what that field does

update 19-01-2022:
"annoying "info' button floating in "Create order". Those 2 (price and type) infos have no action/info/detail on them" 
![unknown](https://user-images.githubusercontent.com/38267570/150133215-05c2a85b-be34-4fa3-a7c8-fe8a98f04f7a.png)

![unknown](https://user-images.githubusercontent.com/38267570/150152972-c71a4920-0a76-4c6d-8508-8b9f19511e87.png)

**Comment by juo-dev** [comment]
Released. Marketplace v1.0
