### ISSUE TITLE
Infinity approve on marketplace

### ISSUE THREAD

**Issue by aviggiano** [mousehaunt/mousehaunt.com#59]
# Description

- Change approve instead of amount for approve total balance (MHT & boosters) 
- Do this on buy order & on sell order

**Comment by aviggiano** [comment]
Now I tried to buy a rare booster and had to approve $MHT again
Is that right the need of approving $MHT every time?
I tried to create an epic order (sale) now and needed to approve twice too

**Comment by juo-dev** [comment]
Released. Marketplace v1.0
