### ISSUE TITLE
Rethink CTAs after order is executed by buyer

### ISSUE THREAD

**Issue by aviggiano** [mousehaunt/mousehaunt.com#65]
> When i buyed showed a buttom to get back to market, maybe whould be nice to put a buttom (could be smaller if needed) to go to inventory

> Another idea is (again) the "add to wallet", like we had in our pre-sales

- [x] Add buttom add to wallet after execute order;
- [x] Add back to mktplace on create order page;
- [x] Add back to mktplace on order details page;
- [x] Add back to mktplace on inventory page;

**Comment by juo-dev** [comment]
Add to inventory after create order.
