### ISSUE TITLE
Executing an order when the seller does not have the assets anymore still redirects successfuly

### ISSUE THREAD

**Issue by aviggiano** [mousehaunt/mousehaunt.com#70]
![seller](https://user-images.githubusercontent.com/3029017/148790071-9bb5f1e5-7d3e-4012-bec0-5a5d79c4dc87.png)
<img width="442" alt="Screen Shot 2022-01-10 at 12 17 13" src="https://user-images.githubusercontent.com/3029017/148790179-857eccc1-538b-4e30-ad72-0257e44bc170.png">

**Comment by karacurt** [comment]
Could not reproduce the error, looks like it was solved on #77

**Comment by juo-dev** [comment]
Released. Marketplace v1.0
