### ISSUE TITLE
Joining the marketplace through a link not always auto connect

### ISSUE THREAD

**Issue by aviggiano** [mousehaunt/mousehaunt.com#71]
<img width="861" alt="Screen Shot 2022-01-10 at 12 19 37" src="https://user-images.githubusercontent.com/3029017/148790621-a28f90ac-0e89-4391-85fe-605929724d0f.png">

**Comment by aviggiano** [comment]
Waiting for #36

**Comment by karacurt** [comment]
adressed on https://github.com/mousehaunt/mousehaunt.com/pull/104
